### ISSUE TITLE
android.hardware.graphics.composer@2.1-service crashes on Ubuntu Touch

### ISSUE THREAD

**Issue by JamiKettunen** [waydroid/android_hardware_waydroid#32]
Adding as a tracking issue so this isn't forgotten about, @dos1 you've been doing a lot of `hwcomposer` related work recently so you should know about this I believe. What were those patches tested on?

I tested this on a Volla Phone 22 / Halium 11 running Ubuntu Touch 16.04 (2022-08-22 / devel channel) with Waydroid 1.2.0 and Android 11 images (so using [`lineage-18.1` branch](https://github.com/waydroid/android_hardware_waydroid/commits/lineage-18.1) here) provided by @aleasto.

He suspected [Mir](https://github.com/MirServer/mir) (2.9.0 even) is missing some required Wayland protocol support, specifically https://wayland.app/protocols/viewporter, so my question is: should I be able to see a similar crash on x86_64 when running the Mir 2.9.0 test compositor as seen in the `logcat` from the phone attached below?
[waydroid-logcat.log](https://github.com/waydroid/android_hardware_waydroid/files/9448430/waydroid-logcat.log)
[waydroid-log.log](https://github.com/waydroid/android_hardware_waydroid/files/9448429/waydroid-log.log)

Fwiw Ubuntu Touch uses a [patched Mir 1.8.2 version](https://gitlab.com/ubports/development/core/packaging/mir/-/tree/ubports/focal/debian/patches) and testing that outside of a device running Ubuntu Touch might be tricky or not possible (I've not tried yet).

Related(?): #12

**Comment by JamiKettunen** [comment]
Got Waydroid working on Mir 2.9.0 `miral-kiosk` (official Android 10 images) after [packaging Mir for Void Linux](https://github.com/JamiKettunen/void-packages/tree/libmir), that's a start :)
![miral-kiosk-2 9 0-waydroid](https://user-images.githubusercontent.com/47358222/187333696-e4151833-1982-40a6-9428-58c537b7a174.png)
Will take a look tomorrow if the same issue can be observed on latest `x86_64` Android 11 images from @aleasto.

**Comment by dos1** [comment]
See https://github.com/waydroid/android_hardware_waydroid/pull/12#issuecomment-1231273310

> What were those patches tested on?

I'm testing them on a Librem 5 phone with phoc 0.21 (using wlroots 0.15.1).

Anyway, I'll make a patch that makes viewporter usage optional later today.

**Comment by JamiKettunen** [comment]
Yea the Android 11 images are also broken on unpatched Mir 2.9.0's `miral-shell` as tested on my desktop with 5.19.4 kernel:
[waydroid-logcat-miral-kiosk-2.9.0.log](https://github.com/waydroid/android_hardware_waydroid/files/9452207/waydroid-logcat-miral-kiosk-2.9.0.log)

Running the same images under `weston --shell=kiosk-shell.so` worked perfectly fine, so it's definitely a Mir upstream issue with protocols; would you @dos1 like to file an issue since you might know the details better or should I do that? I would definitely like this to work on Mir as well so that those patches eventually benefit Ubuntu Touch as well when upgrade to Mir 2.x takes place.

**Comment by dos1** [comment]
Filled as https://github.com/MirServer/mir/issues/2599

FWIW, https://github.com/waydroid/android_hardware_waydroid/pull/33 should already make Waydroid work on compositors that don't support wp_viewporter again, although they're going to miss surface cropping fixes.
