### ISSUE TITLE
audio: Add vanity name (and icon) for Waydroid client

### ISSUE THREAD

**Issue by JamiKettunen** [waydroid/android_hardware_waydroid#39]
Here's an example with `chromium` showing up in `pavucontrol`'s `Playback` tab after playing some audio:
![image](https://user-images.githubusercontent.com/47358222/189590749-0831b0ce-453e-4432-ab42-9f2147bb406c.png)
The same test with Waydroid:
![image](https://user-images.githubusercontent.com/47358222/189590831-9a6f6521-116e-4aba-bb78-90e0732c5615.png)
It would be nice if it showed up similarly; a potential problem I see it shows up as type `ALSA Playback` (does't it require pulse though? or is this just whatever the HAL is naming things?) instead of just `Playback` so I'm not sure if it would support this kind of things.

Also possibly depends on https://github.com/waydroid/waydroid/pull/341 for the icon to show up.

EDIT: Actually I remembered [osu!](https://github.com/ppy/osu) shows up like this so at least the `writer` part should be customizable, don't know about the rest :/
![image](https://user-images.githubusercontent.com/47358222/189591752-743ac795-aa4f-4a92-98c8-2f9b8b4252c4.png)

**Comment by aleasto** [comment]
I don't think we can customize the name.
The part between square brackets is supposed to be the process name.
I'm not sure what process `writer` might be though.

**Comment by aleasto** [comment]
Done:
https://github.com/waydroid/android_external_alsa-plugins/commit/8e6cd7dcff06b3b3b78f60defb65f0d86b79a08a
https://github.com/waydroid/android_external_alsa-plugins/commit/fcc0a2c3002ab0e68694896ded9c76dcd4cc1352

Icon depends on: https://github.com/waydroid/waydroid/pull/341
